name = "CLIMAStateCheck"
uuid = "23213dcc-5489-4aad-bc42-99bf505c6085"
authors = ["Climate Modeling Alliance"]
version = "0.1.0"

[deps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics= "10745b16-79ce-11e8-11f9-7d13ad32a3b2"


[compat]
MPI = "0.12, 0.13"


